/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface AddCosmeticDetailDto {
  myCosmeticId?: number;
  memo?: string;
  ypoint?: number;
  zindex?: number;
  xpoint?: number;
  xPoint?: number;
  yPoint?: number;
  zIndex?: number;
}
