/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { MemberAuthResponse } from './memberAuthResponse';

export interface ApiResponseDTOMemberAuthResponse {
  code?: string;
  message?: string;
  result?: MemberAuthResponse;
}
