/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeData } from './getHomeData';

export interface ApiResponseDTOGetHomeData {
  code?: string;
  message?: string;
  result?: GetHomeData;
}
