/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { FeedListDto } from './feedListDto';

export interface ApiResponseDTOFeedListDto {
  code?: string;
  message?: string;
  result?: FeedListDto;
}
