/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

/**
 * 네이버 이미지 url은 여기에 담아주세요
 */
export interface CreateDetailDirectDto {
  name?: string;
  brand?: string;
  category?: string;
  subCategory?: string;
  price?: number;
  feature?: string;
  memo?: string;
  naverImageUrl?: string;
}
