/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDetailDtoV2 } from './createDetailDtoV2';

export type CreateWishCosmeticsV2Body = {
  /** 캡처 이미지 파일 리스트 */
  captureImages: Blob[];
  /** 네이버 대신 직접 첨부한 상품 이미지 파일 리스트 */
  directImages?: Blob[];
  /** type은 NAVER/DIRECT, NAVER일 경우 naverImageUrl, DIRECT일 경우 directImageIndex 필요 */
  request: CreateDetailDtoV2[];
};
