/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDetailDirectDto } from './createDetailDirectDto';

export type CreateWishCosmeticsDirectBody = {
  /** 사용자가 직접 등록한 이미지 파일이 존재한다면 여기에 담아주세요 */
  productDirectImage?: Blob;
  request: CreateDetailDirectDto;
};
