/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { ProductImage } from './productImage';

export interface CreateDetailDtoV2 {
  name?: string;
  brand?: string;
  category?: string;
  subCategory?: string;
  price?: number;
  feature?: string;
  memo?: string;
  captureImageIndex: number;
  productImage: ProductImage;
}
