/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface FeedDto {
  pouchId?: number;
  pouchScore?: number;
  userName?: string;
  profileImageUrl?: string;
  pouchName?: string;
  pouchImageUrl?: string;
  createdAt?: string;
  emoticonTypeList?: string[];
  favorite?: boolean;
}
