/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { FindMyCosmeticsDto } from './findMyCosmeticsDto';

export interface FeedDetailDto {
  pouchId?: number;
  profileImageUrl?: string;
  userName?: string;
  pouchName?: string;
  emoticonTypeList?: string[];
  myCosmeticsList?: FindMyCosmeticsDto[];
  favorite?: boolean;
}
