/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { FeedDto } from './feedDto';

export interface FeedListDto {
  feedDtoList?: FeedDto[];
  lastId?: number;
  lastScore?: number;
  hasNext?: boolean;
}
