/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type GetFeedListSort = typeof GetFeedListSort[keyof typeof GetFeedListSort];


export const GetFeedListSort = {
  RECOMMENDED: 'RECOMMENDED',
  LATEST: 'LATEST',
} as const;
