/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { Detail } from './detail';

export interface GetHomeData {
  profileUrl?: string;
  nickname?: string;
  wishList?: Detail[];
  myList?: Detail[];
  feed?: Detail[];
}
