/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './apiResponseDTOObject';
export * from './requestMagicLinkParams';
export * from './verifyMagicLinkParams';
