/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type MemberJoinType = typeof MemberJoinType[keyof typeof MemberJoinType];


export const MemberJoinType = {
  GENERAL: 'GENERAL',
  KAKAO: 'KAKAO',
  NAVER: 'NAVER',
} as const;
