/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { MemberJoinType } from './memberJoinType';
import type { MemberRole } from './memberRole';

export interface Member {
  createdDate?: string;
  lastModifiedDate?: string;
  member_id?: number;
  socialId?: number;
  email?: string;
  nickname?: string;
  role?: MemberRole;
  profileImgUrl?: string;
  pushNotice?: boolean;
  joinType?: MemberJoinType;
  active?: boolean;
}
