/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface MemberAuthResponse {
  email?: string;
  nickname?: string;
  accessToken?: string;
  refreshToken?: string;
  newMember?: boolean;
}
