/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type NaverLoginParams = {
/**
 * 네이버 로그인 시 발급받은 code
 */
code: string;
/**
 * state 발급 API로 받은 state
 */
state: string;
};
