/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface PouchItemDetailDto {
  id?: number;
  name?: string;
  brand?: string;
  category?: string;
  subCategory?: string;
  feature?: string;
  memo?: string;
  myCosmeticId?: number;
  xpoint?: number;
  ypoint?: number;
  zindex?: number;
}
