/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { ProductImageType } from './productImageType';

export interface ProductImage {
  type: ProductImageType;
  naverImageUrl?: string;
  directImageIndex?: number;
}
