/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type ReadWishCosmeticsListParams = {
/**
 * 검색 키워드
 */
keyword?: string;
/**
 * 대분류
 */
category?: string;
/**
 * 소분류
 */
subCategory?: string;
/**
 * 최소 가격
 */
minPrice?: number;
/**
 * 최대 가격
 */
maxPrice?: number;
/**
 * 이전에 조회한 목록의 마지막 wishCosmeticsId(무한 스크롤 cursor 방식)
 */
lastId?: number;
/**
 * 조회할 화장품 개수(기본값 10
 */
size?: number;
/**
 * 정렬(desc/asc 중 입력, 기본값은 desc)
 */
sort?: string;
};
