/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface ReadDetailDto {
  wishCosmeticsId?: number;
  productName?: string;
  brand?: string;
  category?: string;
  subCategory?: string;
  feature?: string;
  memo?: string;
  price?: number;
  productImageUrl?: string;
  captureImageUrl?: string;
}
