/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { MyCosmeticsListRequestDtoV2 } from './myCosmeticsListRequestDtoV2';

export type RegisterV2Body = {
  captureImages: Blob[];
  directImages?: Blob[];
  data: MyCosmeticsListRequestDtoV2;
};
