/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { MyCosmeticsRequestDTO } from './myCosmeticsRequestDTO';

export type RegisterBody = {
  captureImages: Blob[];
  data: MyCosmeticsRequestDTO[];
};
