/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * POCHY API 명세서
 * POCHY Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { MyCosmeticsResponseDTO } from './myCosmeticsResponseDTO';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface SliceMyCosmeticsResponseDTO {
  pageable?: PageableObject;
  size?: number;
  content?: MyCosmeticsResponseDTO[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
